"""restructure tour origin mapping for matchcode-based relations

Revision ID: 02775b5d19f0
Revises: 777550b44434
Create Date: 2026-09-17 08:57:22.587236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02775b5d19f0'
down_revision: Union[str, None] = '777550b44434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite unterstuetzt ALTER COLUMN / Index-Neuerstellung nicht direkt -
    # batch_alter_table simuliert dies per Tabellen-Neuerstellung.
    with op.batch_alter_table('tour_origin_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matchcode', sa.String(length=50), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.alter_column('origin_address_id', existing_type=sa.VARCHAR(length=36), nullable=True)
        batch_op.drop_index('ix_tour_origin_mappings_tour_number_prefix')
        batch_op.create_index(batch_op.f('ix_tour_origin_mappings_tour_number_prefix'), ['tour_number_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_tour_origin_mappings_matchcode'), ['matchcode'], unique=False)
        batch_op.drop_column('label')

    with op.batch_alter_table('tour_origin_mappings', schema=None) as batch_op:
        batch_op.alter_column('matchcode', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_origin_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_tour_origin_mappings_matchcode'))
        batch_op.drop_index(batch_op.f('ix_tour_origin_mappings_tour_number_prefix'))
        batch_op.create_index('ix_tour_origin_mappings_tour_number_prefix', ['tour_number_prefix'], unique=True)
        batch_op.alter_column('origin_address_id', existing_type=sa.VARCHAR(length=36), nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('matchcode')
    # ### end Alembic commands ###
