"""add tours and tour references

Revision ID: 0df934345455
Revises: f8c0b9d0973f
Create Date: 2026-09-17 06:53:29.179671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df934345455'
down_revision: Union[str, None] = 'f8c0b9d0973f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tours',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tour_number', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('carrier_id', sa.String(length=36), nullable=True),
    sa.Column('tour_date', sa.Date(), nullable=True),
    sa.Column('loading_date', sa.Date(), nullable=True),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('invoiced_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('invoice_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tours_tour_number'), 'tours', ['tour_number'], unique=True)

    # SQLite unterstuetzt ALTER COLUMN / ADD CONSTRAINT nicht direkt - batch_alter_table
    # simuliert dies per Tabellen-Neuerstellung (noetig fuer Tests mit SQLite).
    with op.batch_alter_table('audit_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('shipment_id',
                   existing_type=sa.VARCHAR(length=36),
                   nullable=True)
        batch_op.create_foreign_key('fk_audit_results_tour_id_tours', 'tours', ['tour_id'], ['id'])

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_shipments_tour_id_tours', 'tours', ['tour_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shipments_tour_id_tours', type_='foreignkey')
        batch_op.drop_column('tour_id')

    with op.batch_alter_table('audit_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_results_tour_id_tours', type_='foreignkey')
        batch_op.alter_column('shipment_id',
                   existing_type=sa.VARCHAR(length=36),
                   nullable=False)
        batch_op.drop_column('tour_id')

    op.drop_index(op.f('ix_tours_tour_number'), table_name='tours')
    op.drop_table('tours')
    # ### end Alembic commands ###
