"""add toll km and special agreement surcharge

Revision ID: 562f67719b4a
Revises: 02775b5d19f0
Create Date: 2026-09-17 09:41:32.323432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562f67719b4a'
down_revision: Union[str, None] = '02775b5d19f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_agreement_surcharges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tour_number_prefix', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_special_agreement_surcharges_tour_number_prefix'), 'special_agreement_surcharges', ['tour_number_prefix'], unique=True)
    op.add_column('tours', sa.Column('toll_km', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'toll_km')
    op.drop_index(op.f('ix_special_agreement_surcharges_tour_number_prefix'), table_name='special_agreement_surcharges')
    op.drop_table('special_agreement_surcharges')
    # ### end Alembic commands ###
