"""initial schema

Revision ID: 710bc7c6f533
Revises: 
Create Date: 2026-09-16 20:18:35.045912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710bc7c6f533'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_text', sa.String(length=500), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geocoding_provider', sa.String(length=50), nullable=True),
    sa.Column('geocoding_confidence', sa.Float(), nullable=True),
    sa.Column('geocoding_precision', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carriers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('carrier_code', sa.String(length=50), nullable=False),
    sa.Column('billing_rules_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carriers_carrier_code'), 'carriers', ['carrier_code'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('tax_identifier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.Enum('EMAIL_SYNC', 'LADELISTE_UPLOAD', 'MANUAL_UPLOAD', name='import_source_type'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', name='import_job_status'), nullable=False),
    sa.Column('records_total', sa.Integer(), nullable=False),
    sa.Column('records_successful', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_report_reference', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailboxes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('configuration_reference', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PRUEFER', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_value_json', sa.JSON(), nullable=True),
    sa.Column('new_value_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_message_id', sa.String(length=998), nullable=False),
    sa.Column('mailbox_id', sa.String(length=36), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('recipients', sa.Text(), nullable=False),
    sa.Column('cc_recipients', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.Enum('RECEIVED', 'PROCESSING', 'PROCESSED', 'DUPLICATE', 'ERROR', name='email_processing_status'), nullable=False),
    sa.Column('processing_notes', sa.Text(), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mailbox_id', 'external_message_id', name='uq_email_mailbox_message')
    )
    op.create_index(op.f('ix_emails_external_message_id'), 'emails', ['external_message_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_number', sa.String(length=100), nullable=True),
    sa.Column('transport_order_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('transport_date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('carrier_id', sa.String(length=36), nullable=True),
    sa.Column('origin_address_id', sa.String(length=36), nullable=True),
    sa.Column('destination_address_id', sa.String(length=36), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('pallets', sa.Integer(), nullable=True),
    sa.Column('packages', sa.Integer(), nullable=True),
    sa.Column('loading_meters', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('volume_m3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('invoiced_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('invoice_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['destination_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['origin_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_invoice_number'), 'shipments', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_number'), 'shipments', ['shipment_number'], unique=False)
    op.create_index(op.f('ix_shipments_transport_order_number'), 'shipments', ['transport_order_number'], unique=False)
    op.create_table('tariffs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tariff_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('carrier_id', sa.String(length=36), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RELEASED', 'ARCHIVED', name='tariff_status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_tariff_code'), 'tariffs', ['tariff_code'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_reference', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_file_hash'), 'attachments', ['file_hash'], unique=False)
    op.create_table('audit_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('tariff_id', sa.String(length=36), nullable=True),
    sa.Column('reference_distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('invoiced_distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('invoiced_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference_percent', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('status', sa.Enum('BESTANDEN', 'ABWEICHUNG', 'MANUELLE_PRUEFUNG', 'FEHLER', 'FREIGEGEBEN', 'RUECKFRAGE', name='audit_status'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=True),
    sa.Column('origin_latitude', sa.Float(), nullable=False),
    sa.Column('origin_longitude', sa.Float(), nullable=False),
    sa.Column('destination_latitude', sa.Float(), nullable=False),
    sa.Column('destination_longitude', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('routing_profile', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariff_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tariff_id', sa.String(length=36), nullable=False),
    sa.Column('rule_type', sa.Enum('BASE_PLUS_KM', 'RELATION', 'WEIGHT_BRACKET', 'PALLET', 'LOADING_METER', 'ZONE', 'ALL_IN', 'MINIMUM_FREIGHT', 'COUNTRY_BORDER_SURCHARGE', 'TIME_DEPENDENT', name='tariff_rule_type'), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_rule_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_result_id', sa.String(length=36), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'WARNING', 'FAILED', 'MANUAL_REVIEW', 'ERROR', name='audit_rule_status'), nullable=False),
    sa.Column('actual_value', sa.String(length=500), nullable=True),
    sa.Column('expected_value', sa.String(length=500), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_result_id'], ['audit_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attachment_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.Enum('FRACHTRECHNUNG', 'LADELISTE', 'TRANSPORTAUFTRAG', 'ABLIEFERBELEG', 'PREISANGEBOT', 'MAUTNACHWEIS', 'WARTEZEITNACHWEIS', 'PALETTENTAUSCHBELEG', 'SONSTIGES', name='document_type'), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('ocr_status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'ERROR', name='ocr_status'), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attachment_id')
    )
    op.create_table('document_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('ocr_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_bbox', sa.JSON(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surcharge_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('surcharge_type', sa.Enum('DIESEL_ENERGY', 'TOLL', 'ADR', 'WAITING_TIME', 'ADDITIONAL_LOADING_POINT', 'ADDITIONAL_UNLOADING_POINT', 'NOTIFICATION', 'LIFTING_PLATFORM', 'FORKLIFT_ESCORT', 'OVERSIZE_BULKY_GOODS', 'FERRY_ISLAND', 'CUSTOMS_BORDER_CLEARANCE', 'NIGHT_WEEKEND_HOLIDAY', 'FAILED_TRIP', 'FAILED_DELIVERY', 'PALLET_EXCHANGE', 'DEMURRAGE', 'EXPRESS_FIXED_DATE', 'OTHER', name='surcharge_type'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('claimed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('evidence_document_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ALLOWED', 'PARTIALLY_ALLOWED', 'REJECTED', 'MANUAL_REVIEW', name='surcharge_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surcharge_claims')
    op.drop_table('extracted_fields')
    op.drop_table('document_pages')
    op.drop_table('documents')
    op.drop_table('audit_rule_results')
    op.drop_table('tariff_rules')
    op.drop_table('routing_results')
    op.drop_table('audit_results')
    op.drop_index(op.f('ix_attachments_file_hash'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_tariffs_tariff_code'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_shipments_transport_order_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_invoice_number'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_emails_external_message_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('mailboxes')
    op.drop_table('import_jobs')
    op.drop_table('customers')
    op.drop_index(op.f('ix_carriers_carrier_code'), table_name='carriers')
    op.drop_table('carriers')
    op.drop_table('addresses')
    # ### end Alembic commands ###
