"""add tour origin mappings and shipment sequence

Revision ID: 777550b44434
Revises: 0df934345455
Create Date: 2026-09-17 08:05:37.236135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777550b44434'
down_revision: Union[str, None] = '0df934345455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_origin_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tour_number_prefix', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('origin_address_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['origin_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_origin_mappings_tour_number_prefix'), 'tour_origin_mappings', ['tour_number_prefix'], unique=True)
    op.add_column('shipments', sa.Column('sequence_in_tour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'sequence_in_tour')
    op.drop_index(op.f('ix_tour_origin_mappings_tour_number_prefix'), table_name='tour_origin_mappings')
    op.drop_table('tour_origin_mappings')
    # ### end Alembic commands ###
