"""add unloading point count to shipments

Revision ID: f8c0b9d0973f
Revises: 710bc7c6f533
Create Date: 2026-09-16 20:42:53.210082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c0b9d0973f'
down_revision: Union[str, None] = '710bc7c6f533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='1' backfuellt bestehende Zeilen (sonst schlaegt ADD
    # COLUMN NOT NULL auf einer bereits befuellten Tabelle fehl, z. B. Postgres).
    op.add_column('shipments', sa.Column('unloading_point_count', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'unloading_point_count')
    # ### end Alembic commands ###
